server {
    listen 80;
    server_name _;

    root /app/public;
    index index.php index.html;

    # Musi być zgodne z post_max_size w PHP, inaczej Nginx odrzuci upload (413).
    client_max_body_size 512M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
    }
}
